# This file is autogenerated, do not modify
import packedjson, asyncfutures,asyncdispatch,xmlparser,xmltree,strutils,db_mysql,threadpool,times,sequtils,tables
import utils/client
import credentials

export client.new
const awsApiMD_apiVersion* = "2016-11-15"
const awsApiMD_endpointPrefix* = "ec2"
const awsApiMD_protocol* = "ec2"
const awsApiMD_serviceAbbreviation* = "Amazon EC2"
const awsApiMD_serviceFullName* = "Amazon Elastic Compute Cloud"
const awsApiMD_serviceId* = "EC2"
const awsApiMD_signatureVersion* = "v4"
const awsApiMD_uid* = "ec2-2016-11-15"
const awsApiMD_xmlNamespace* = "http://ec2.amazonaws.com/doc/2016-11-15"
defineClient(EC2)

